Added rclcpp::Rate to lidarThreadFunc to reduce CPU load
Myzhar/ldrobot-lidar-ros2 pull request #21
Opened 2024-05-19 09:48 UTC by JustusBraun

The lidarThreadFunc did active waiting for scans to be available which led to high cpu usage and powerdraw on battery powered devices.

The pthread.h include in "ldlidar_component/ldlidar_driver/src/logger/log_module.cpp" was necessary to compile the project.

2024-05-24 15:53 UTC, Myzhar reviewed
I really missed the sleep. You are right, it is required.

I'm not sure it is good to set a fixed rate, why not changing it according to the value of `lidar_scan_freq`?

2024-05-24 15:55 UTC, Myzhar requested changes
Evaluate a variable sleep rate instead of a fixed value

2024-05-26 13:01 UTC, JustusBraun commented
You are right a variable rate makes more sense. I have implemented the variable sleep rate, in case there are no subscribers connected to the topic or `GetLidarScanFreq` returns false the thread will sleep for a tenth of a second.

2024-05-27 06:48 UTC, Myzhar approved these changes

2024-05-27 06:49 UTC, merged